maintainer       "Gábor Vészi"
maintainer_email "veszig@done.hu"
license          "Apache 2.0"
description      "Sets up gentoo specific config files and directories"
version          "0.2.1"
recipe           "gentoo", "Basic gentoo configuration"
recipe           "gentoo::portage", "Portage specific configuration files"
recipe           "gentoo::hardened", "Hardened Gentoo modifications"
supports         "gentoo"
depends          "eix"
